apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    io.kompose.service: app
spec:
  type: NodePort          # 
  selector: 
    app: app
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30080     
